/* eslint-env browser */

(function initMarkdown(root, factory) {
  const api = factory();
  if (typeof module !== "undefined" && module.exports) {
    module.exports = api;
  } else {
    root.ArchNoteMarkdown = api;
  }
})(typeof globalThis !== "undefined" ? globalThis : this, function markdownFactory() {
  "use strict";

  const MARKER = "arch-note-zotero-report";

  function escapeHtml(value) {
    return String(value || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#39;");
  }

  function markdownToNoteHTML(markdown, metadata) {
    const meta = metadata || {};
    const title = escapeHtml(meta.title || "Arch Note 导读");
    const model = escapeHtml(meta.model || "DeepSeek");
    const generatedAt = escapeHtml(meta.generatedAt || new Date().toISOString());
    const body = escapeHtml(markdown || "");
    return [
      `<div data-source="${MARKER}">`,
      `<h1>${title}</h1>`,
      `<p><strong>Generated by:</strong> Arch Note Zotero DeepSeek (${model})</p>`,
      `<p><strong>Generated at:</strong> ${generatedAt}</p>`,
      `<pre style="white-space: pre-wrap; font-family: var(--font-family-monospace, monospace);">${body}</pre>`,
      "</div>"
    ].join("");
  }

  function noteContainsReport(html) {
    return String(html || "").includes(MARKER);
  }

  return {
    MARKER,
    escapeHtml,
    markdownToNoteHTML,
    noteContainsReport
  };
});

